---
apiVersion: ec2.aws.upbound.io/v1beta1
kind: EIP
metadata:
  name: dev-nat
spec:
  forProvider:
    region: ap-south-1
    vpc: true
    tags:
      Name: dev-nat
---
apiVersion: ec2.aws.upbound.io/v1beta1
kind: NATGateway
metadata:
  name: dev-nat
spec:
  forProvider:
    region: ap-south-1
    connectivityType: public
    allocationIdRef:
      name: dev-nat
    subnetIdSelector:
      matchLabels:
        name: dev-public-ap-south-1a
    tags:
      Name: dev-nat
